# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 18:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import hotel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0003_auto_20170526_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField()),
                ('cama_casal', models.IntegerField(default=1, verbose_name='Qtd. camas de casal')),
                ('cama_solteiro', models.IntegerField(default=0, verbose_name='Qtd. camas de solteiro')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('S', 'Sujo'), ('M', 'Esperando Manutenção')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateTimeField(default=datetime.datetime(2017, 5, 26, 18, 42, 8, 516835, tzinfo=utc), verbose_name='Data da Reserva')),
                ('status', models.CharField(choices=[('P', 'Pré-reserva'), ('O', 'Confirmada'), ('N', 'No-Show'), ('W', 'Walk-in'), ('F', 'Finalizada'), ('C', 'Cancelada')], max_length=1)),
                ('dead_line', models.DateField(default=hotel.models.calcula_deadline, verbose_name='Dead Line')),
                ('historico', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_quarto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, unique=True)),
                ('descrição', models.TextField(blank=True, null=True)),
                ('preco_base', models.PositiveIntegerField(verbose_name='Preço Base')),
                ('pessoa_adicional', models.PositiveIntegerField(verbose_name='Custo Pessoa Adicional')),
            ],
        ),
        migrations.AddField(
            model_name='quarto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.tipo_quarto'),
        ),
    ]
