# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 19:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamento', models.DecimalField(decimal_places=2, max_digits=20)),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('A', 'Agendado para'), ('P', 'Pago')], default='A', max_length=1)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaQuarto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField()),
                ('saida', models.DateTimeField()),
                ('qtd_adultos', models.PositiveIntegerField(verbose_name='Qtd. Adultos')),
                ('qtd_crianca', models.PositiveIntegerField(verbose_name='Qtd. Crianças')),
                ('checkin', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Check in')),
                ('checkout', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Check out')),
                ('custo', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Quarto')),
            ],
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 26, 19, 35, 49, 159867, tzinfo=utc), verbose_name='Data da Reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('R', 'Pré-reserva'), ('P', 'Confirmada'), ('N', 'No-Show'), ('W', 'Walk-in'), ('O', 'Ocupado'), ('F', 'Finalizada'), ('C', 'Cancelada')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tipo_quarto',
            name='pessoa_adicional',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Custo Pessoa Adicional'),
        ),
        migrations.AlterField(
            model_name='tipo_quarto',
            name='preco_base',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Preço Base'),
        ),
        migrations.AddField(
            model_name='reservaquarto',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Reserva'),
        ),
        migrations.AddField(
            model_name='reservapagamento',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Reserva'),
        ),
        migrations.AddField(
            model_name='reservapagamento',
            name='reserva_quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.ReservaQuarto'),
        ),
    ]
