# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 19:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20170526_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 26, 19, 41, 6, 374946, tzinfo=utc), verbose_name='Data da Reserva'),
        ),
        migrations.AlterField(
            model_name='reservaquarto',
            name='entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
