# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 19:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20170526_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 26, 19, 46, 29, 853885, tzinfo=utc), verbose_name='Data da Reserva'),
        ),
        migrations.AlterField(
            model_name='reservaquarto',
            name='checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservaquarto',
            name='checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservaquarto',
            name='entrada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservaquarto',
            name='saida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
