# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 19:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0025_auto_20170617_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaquarto',
            name='checkout',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 17, 19, 30, 29, 797094, tzinfo=utc), verbose_name='Data da Reserva'),
        ),
    ]
