# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 15:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0027_auto_20170621_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaquarto',
            name='checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservaquarto',
            name='checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 21, 15, 26, 20, 993328, tzinfo=utc), verbose_name='Data da Reserva'),
        ),
    ]
