# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-10 19:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0048_auto_20171210_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 10, 19, 21, 54, 301699, tzinfo=utc), verbose_name='Data da Reserva'),
        ),
    ]
