# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 19:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0002_auto_20170526_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 26, 19, 35, 49, 156530, tzinfo=utc)),
        ),
    ]
