# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 14:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0007_auto_20170527_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 27, 14, 33, 2, 308924, tzinfo=utc)),
        ),
    ]
