# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 13:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0012_auto_20170531_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 1, 13, 10, 13, 169722, tzinfo=utc)),
        ),
    ]
