# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 16:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0022_auto_20170615_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 17, 16, 47, 4, 965204, tzinfo=utc)),
        ),
    ]
