# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-19 11:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0045_auto_20171118_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 11, 40, 44, 963415, tzinfo=utc)),
        ),
    ]
