# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-10 17:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0048_auto_20171210_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 10, 17, 42, 6, 15945, tzinfo=utc)),
        ),
    ]
