# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 15:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo_pessoa', models.CharField(choices=[('F', 'Pessoa Fisica'), ('J', 'Pessoa Juridica')], default='F', max_length=1)),
                ('data_criacao', models.DateTimeField(default=datetime.datetime(2017, 5, 20, 15, 11, 35, 626533, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contato', models.CharField(choices=[('C', 'Celular'), ('E', 'Email'), ('W', 'Whatsapp'), ('F', 'Telefone Fixo'), ('O', 'Outro')], default='C', max_length=1)),
                ('contato', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
            ],
        ),
    ]
