# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 00:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 25, 0, 1, 25, 528970, tzinfo=utc)),
        ),
    ]
