# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 13:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_auto_20170526_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 27, 13, 58, 26, 317603, tzinfo=utc)),
        ),
    ]
