# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 14:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0014_auto_20170601_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 4, 14, 26, 53, 986677, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contato',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='cliente.Cliente'),
        ),
    ]
