# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 14:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0015_auto_20170604_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('C', 'CPF'), ('R', 'RG'), ('M', 'Carteira de Motorista'), ('O', 'Outro')], default='C', max_length=1)),
                ('documento', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 4, 14, 41, 9, 951537, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='documento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='cliente.Cliente'),
        ),
    ]
