# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 00:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0018_auto_20170604_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 15, 0, 39, 5, 946668, tzinfo=utc)),
        ),
    ]
