# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 14:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0028_auto_20170617_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 21, 14, 10, 39, 21184, tzinfo=utc)),
        ),
    ]
