# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-17 19:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0030_auto_20170621_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 17, 19, 35, 12, 701319, tzinfo=utc)),
        ),
    ]
