# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-18 12:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0031_auto_20171117_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 18, 12, 57, 12, 580207, tzinfo=utc)),
        ),
    ]
