# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-18 18:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0040_auto_20171118_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 18, 18, 26, 7, 90108, tzinfo=utc)),
        ),
    ]
