# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-18 20:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0044_auto_20171118_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 18, 20, 6, 17, 569693, tzinfo=utc)),
        ),
    ]
