# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-11 14:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('cliente', '0053_auto_20171211_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 14, 58, 18, 912854, tzinfo=utc)),
        ),
    ]
