# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-18 17:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20171118_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaproduto',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='reservaproduto',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 11, 18, 17, 43, 25, 964308, tzinfo=utc)),
        ),
    ]
