# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-18 17:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20171118_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservaproduto',
            old_name='custo',
            new_name='total',
        ),
        migrations.AlterField(
            model_name='reservaproduto',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 11, 18, 17, 43, 52, 861309, tzinfo=utc)),
        ),
    ]
