# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-18 20:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0011_auto_20171118_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='limite_dia',
            field=models.IntegerField(default=0, verbose_name='Limite por dia'),
        ),
        migrations.AlterField(
            model_name='reservaproduto',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 11, 18, 20, 6, 17, 577223, tzinfo=utc)),
        ),
    ]
