# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-18 21:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0012_auto_20171118_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaproduto',
            name='status',
            field=models.CharField(choices=[('P', 'Pré-reserva'), ('C', 'Confirmada'), ('O', 'Paga'), ('E', 'Cancelada')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='reservaproduto',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 11, 18, 21, 50, 54, 671934, tzinfo=utc)),
        ),
    ]
