# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-19 11:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0013_auto_20171118_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaproduto',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 11, 19, 11, 40, 44, 968978, tzinfo=utc)),
        ),
    ]
