# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-10 14:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0014_auto_20171119_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaproduto',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 12, 10, 14, 56, 3, 255057, tzinfo=utc)),
        ),
    ]
