# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-11 14:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0019_auto_20171211_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaproduto',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 12, 11, 14, 56, 51, 868707, tzinfo=utc)),
        ),
    ]
