# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-11 14:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0020_auto_20171211_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaproduto',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 12, 11, 14, 58, 18, 920702, tzinfo=utc)),
        ),
    ]
